### ISSUE TITLE
Better warnings when static site builds fail

### ISSUE THREAD

**Issue by julia-allyce** [bitovi/documentjs#108]

**Comment by immist** [comment]
+1 on this. When using DocumentJS for a Live Style Guide, and for example the "siteDefaults" are not configured correctly in the documentjs.json, the only error output is
 ```
Generating styles at styleguide

/usr/local/Cellar/node/0.10.5/lib/node_modules/documentjs/node_modules/q/q.js:126
                    throw e;
                          ^
Error: ENOENT, open '/usr/local/Cellar/node/0.10.5/lib/node_modules/documentjs/site/templates/b4b386add82ed7f6ae5fac12c924ac5b/layout.mustache'
```
which is not especially helpful.

**Comment by jandjorgensen** [comment]
@julia-allyce Do you have any details on this? Closing unless there are a few examples.

**Comment by julia-allyce** [comment]
@jandjorgensen sorry I think this was something Justin asked me to post...its been too long to remember the details :/
