### ISSUE TITLE
Ordering @style blocks

### ISSUE THREAD

**Issue by jandjorgensen** [bitovi/documentjs#121]
Allow ordering of @style blocks in a @stylesheet page

**Comment by lkodai** [comment]
Don't we have this functionality with the @parent tag? @adrifolio and I have been ordering @style blocks on a @stylesheet. I don't think extending the functionality to the @style tag is necessary.

**Comment by jandjorgensen** [comment]
Currently, the `@style` blocks will always be in alphabetical order--I believe using the `@parent` tag will not order them either at this point (which is easier to add back in). Ideally, they would appear in the page in the same order they do in the file, correct?

**Comment by lkodai** [comment]
Parent tag totally works with style blocks in the same file or in different files. For a client project we've reordered sections for documentation flow (moving "utilities" down to the bottom of a documentation page, despite the variables being declared at the top of the less file), and pulling documentation for one section (like Typography) in from two files (typography.less and type-custom.less)

**Comment by jandjorgensen** [comment]
Closing per @lkodai's comment
