### ISSUE TITLE
Source link incorrect when version references a #tag

### ISSUE THREAD

**Issue by kylegifford** [bitovi/documentjs#165]
Given a documentjs.json file containing the following source:

`"source": "https://github.com/repo/project#branch"`

The source link is generated as this link, which is invalid:

`https://github.com/repo/project#branch/path`

Instead, it should parse the # if it's a Github URL, and update the URL to:

`https://github.com/repo/project/tree/branch/path`

**Comment by jandjorgensen** [comment]
Determined along with @kylegifford that the links relying on the `#` syntax should use the `git://` protocol since they are installed with `npm`.

For instance,
"source": "git://github.com/repo/project#branch"

For a tag, the `tree/branch/path` syntax must be used for https.
