### ISSUE TITLE
Create a Linode StackScript 

### ISSUE THREAD

**Issue by marshallswain** [bitovi/documentjs#166]
To help setup a server for publishing. 

Linode allows creating a new server with what they call a StackScript, which is basically a souped-up shell script.  This would allow a new, ready-to-go Strider server in a couple minutes.

https://www.linode.com/docs/platform/stackscripts

**Comment by jandjorgensen** [comment]
Closing in process of cleaning out the backlog. If anything, we should reopen to discuss sovling the generic problem of deploying on something more complicated than gh-pages at all.
