### ISSUE TITLE
Default styles for properties should not show box

### ISSUE THREAD

**Issue by daffl** [bitovi/documentjs#176]
Currently the default style used for properties is showing an empty box like this:

![screen shot 2015-06-25 at 11 19 43 am](https://cloud.githubusercontent.com/assets/338316/8360779/29d13fec-1b2c-11e5-9127-a793ffa2e68f.png)

It would be nicer if if was only the header when there is no nested text.

**Comment by marshallswain** [comment]
Same as #134
