### ISSUE TITLE
Space after commas, in comma separated paths given in "pattern" property of glob in documentjs.json breaks.

### ISSUE THREAD

**Issue by gdad-s-river** [bitovi/documentjs#240]
For example if I do 
`      "glob": {
        "pattern": "{*.md, lego4-comp-search/index.js,lego4-comp-search/README.md}"
      },`
instead of 
`      "glob": {
        "pattern": "{*.md,lego4-comp-search/index.js,lego4-comp-search/README.md}"
      },`
it wouldn't read lego4-comp-search/index.js at all...

**Comment by justinbmeyer** [comment]
Thanks for reporting.  This functionality is totally inherited from https://github.com/isaacs/node-glob.  Please create an issue there if you'd like to see this changed.
