### ISSUE TITLE
UNMET PEER DEPENDENCY jquery@1.11.3

### ISSUE THREAD

**Issue by leoj3n** [bitovi/documentjs#250]
When having `jquery@3.0.0` specified in `package.json` of a DoneJS plugin (which has a dependency of `documentjs@0.4.41`, which depends upon `can@2.3.8`) this WARN will appear:

```
npm WARN can@2.3.8 requires a peer of jquery@>=1.9.0 <3.0.0 but none was installed.
```

I don't really understand the game plan for using jQuery 3.0 going forward.

**Comment by justinbmeyer** [comment]
CanJS 3.0 works fine along side jQuery 3.0.  But jQuery doesn't.

We need to make a release of documentjs that uses CanJS 3.0, which doesn't use peer dependencies.
