### ISSUE TITLE
Error with @demo tag after updating to 0.5.2

### ISSUE THREAD

**Issue by kylegifford** [bitovi/documentjs#287]
I upgraded an existing DocJS site from 0.4.4 to 0.5.2. On a page with the `@demo` tag, I get the following error. This does not happen on 0.4.4.

![screenshot 2018-06-18 16 21 13](https://user-images.githubusercontent.com/4341379/41565407-ec2a96f0-7313-11e8-9550-5dfeb158dfcd.png)
![screenshot 2018-06-18 16 44 28](https://user-images.githubusercontent.com/4341379/41566057-f0cb578c-7316-11e8-8f35-1dcfe9911b23.png)

**Comment by tracer99** [comment]
I was looking at this myself as well. If you check out the project, two tests are failing

>   1) documentjs/lib/generators/html
>        can push out dev mode static:

> 2) documentjs/lib/generators/html
>        "after each" hook for "body is rendered as a mustache template prior to markdown":

 
Don't know if related.

**Comment by Eruedraith** [comment]
I'm running into the same issue, does anyone have a fix on this yet?

**Comment by tracer99** [comment]
@Eruedraith only a workaround. We're putting int `@iframe` tags for now until this gets fixed.

**Comment by Eruedraith** [comment]
Thanks for the quick response @tracer99 
You are putting this into the stylesheet? 
`@iframe @demo /demos/typography.html`

**Comment by tracer99** [comment]
not exactly
`@iframe @demo /demos/typography.html`

then at some point, if it gets fixed, just do a search and replace for `@iframe` and replace with `@demo`

**Comment by Eruedraith** [comment]
Okay that's what I figured, thank you. 
So for the DocumentCSS portion, there won't be any tabs for now then?

Thanks for the patience, sorry this is the first time working with Documentjs.

**Comment by tracer99** [comment]
Yeah, not ideal, but it works. 
For small global styles, we're adding the following above the `@iframe` tag

```
* ```html
* <button class='largeBtn'></button>
* ```
```

**Comment by Eruedraith** [comment]
Thanks so much @tracer99! I appreciate the workaround.
I'm looking forward to trying out the `@demo` when it's fixed. :)

**Comment by alabbas-ali** [comment]
Is it possible to fix it? I had to overwrite the static.js with a static one, Also adding multiple Demos in the same md file appears not to work. there are some issues with 
"demo_frame" 
this part of the code
$('.demo_wrapper', this.element).each(function() {
				var wrapper = $(this);
				new DemoFrame(wrapper);
				
				if(wrapper.data('demoHeight')) {
					iframe.height(wrapper.data('demoHeight'));
				}
			});
suppose to loop over all the demos. but it appers that this line new DemoFrame(wrapper); break the code for some resone. 
I will appreciate a fix. :)

**Comment by johnnylord** [comment]
It has been awhile : (. I'm still waiting for the bug fixed.

**Comment by m-mujica** [comment]
hey guys sorry for the looong delay to gets this fixed. I just published 0.5.5 and it should take care of this error. Please let me know if it works for you.
