### ISSUE TITLE
Documentation not automatically generated for IIFEs

### ISSUE THREAD

**Issue by booc0mtaco** [bitovi/documentjs#80]
Example:

	/**
	 * Documentation like this works as expected
	 */
	nameOfMethod: function() {
		// returns a value
	},

	/**
	 * But this won't show up after you run documentjs
	 */
	nameOfAnotherMethod: (function() {
		var memoizedCache = {};
		return function() {
			// some caching checks
		}
	})(),

This generates a "no name for" error in the console output. According to <http://documentjs.com/docs/documentjs.tags.function.html>, immediately-invoked function expressions can't be inferred (yet). Is this fixable? 

Workaround: use `@function`, `@parent`, and `@param`. The problem with that is there is no indication normal doc-block won't work for these types of expressions.

**Comment by jandjorgensen** [comment]
Closing this as a won't-fix for now as part of issue cleanup. We probably don't want to go down the road of making too many assumptions, but if the discussion needs to continue we can reopen.
