### ISSUE TITLE
documentjs.com : Bitovi menu incorrect links

### ISSUE THREAD

**Issue by tomgreever** [bitovi/documentjs#86]
This menu is using the old Bitovi.com nav and links. Should be updated to change Consulting to Development and add Design, change People to About: 
![screen shot 2014-12-10 at 12 36 23 pm](https://cloud.githubusercontent.com/assets/326843/5381679/48b6424e-8069-11e4-92fb-39b0ad0154ff.png)

**Comment by jandjorgensen** [comment]
Fixed in #187
