### ISSUE TITLE
docObject references need to be updated and tested

### ISSUE THREAD

**Issue by daffl** [bitovi/documentjs#88]
The `data` reference in https://github.com/bitovi/documentjs/blob/master/lib/generators/html/write/doc_object.js#L42 needs to be changed to `docObject`. This also needs to be tested (the error occurs when rendering an individual mustache file).

**Comment by jandjorgensen** [comment]
Fixed in #735a79ba1dde9b4e0e6d93f410b621dda49b3fe3
