### ISSUE TITLE
Gaze@0.6.4 dependency build failed

### ISSUE THREAD

**Issue by marnusw** [bitovi/documentjs#91]
I had an issue installing via npm because the [gaze](https://www.npmjs.com/package/gaze) dependency does a rebuild which failed. It seems a number of people have experienced a similar issue with gaze here shama/gaze#110.

The answer proposed by Shama on the issue above is to peg to `gaze@0.5.x` for the time being, which I've done in my [fork](https://github.com/marnusw/documentjs) of documentjs, and this indeed allows the install to complete because v0.5 comes with pre-built binaries. (I'm just not sure if your watcher will still work with this version, but since I won't use be using it, it suits me to just have the install passing.)

I'm not necessarily suggesting that you revert to the older version, especially if this issue has never come up from another user before. Just thought I'd mention it and reference the gaze issue in case it helps someone else. Hopefully Shama will have this problem fixed soon as he seems to indicate.

For the record, I'm using `Ubuntu 12.04 LTS`, `Node v0.11.14`, and `npm v2.0.0`. Ubuntu runs in a Vagrant/Virtual Box VM, but since I'm not installing in a shared folder I doubt that is an issue.

**Comment by ccummings** [comment]
Same as this issue here: https://github.com/shama/gaze/issues/173

Perhaps we switch out gaze for chokidar which supports node 0.11.x and iojs?

**Comment by justinbmeyer** [comment]
I'll switch to the prebuilt for now.  @ccummings I've got no problems with switching everything to chokidar.
