### ISSUE TITLE
Tags don't match with versions on npmjs.org.

### ISSUE THREAD

**Issue by trusktr** [bitovi/documentjs#92]
I noticed the tags don't match the versions published on npmjs.org.

**Comment by justinbmeyer** [comment]
What do you mean?  The versions available:

```
npm view documentjs versions
 
[ '0.1.0',
  '0.1.1',
  '0.1.2',
  '0.1.3',
  '0.2.0' ]
```

The site has 1.0 and 2.0.  They match.  We only have 0.1.X and 0.2.X versions because there's no point in having each patch version.

**Comment by trusktr** [comment]
What I mean is when you look at the tags here on GitHub you'll see

```
Branches  Tags
v3.2.3
v3.2.2
v3.2.1
v3.2.0
v1.0
```

Those seem to be different than 

```
npm view documentjs versions

[ '0.1.0',
  '0.1.1',
  '0.1.2',
  '0.1.3',
  '0.2.0' ]
```

**Comment by justinbmeyer** [comment]
Those are legacy for the old JMVC.

**Comment by trusktr** [comment]
Ah, for sure. Planning to update them? I was using a package manager that looks at tags for deps.
