### ISSUE TITLE
Images missing on DocumentJS website.

### ISSUE THREAD

**Issue by leebrandt** [bitovi/documentjs#99]
When I view http://www.javascriptmvc.com/docs/DocumentJS.html#section_Features

I scroll down below the code comment example, the:

This is what you should see when you open crm\docs.html:

The image below is missing. In fact I get 404s for both images on that page in chrome dev console:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.javascriptmvc.com/jmvc/site/images/crm_doc_demo_1.png 
Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.javascriptmvc.com/jmvc/site/images/crm_doc_demo_2.png

Hope this helps.

~Lee

**Comment by justinbmeyer** [comment]
Thanks.  DocumentJS's documentation is now on its own page:  http://documentjs.com .  Please use that.

**Comment by Guamaso** [comment]
Should http://www.javascriptmvc.com/docs/DocumentJS.html redirect to http://documentjs.com/? Or at least have a deprecated header in it that explains where new docs are?
